services:
  builder:
    image: builder
    build: ./builder

  db:
    image: database
    build: ./database
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mangos
  
  realmd:
    depends_on:
      - builder
      - db
    image: realmd
    build: ./realmd
    ports:
      - "3724:3724"
    restart: always
    environment:
      LOGIN_DATABASE_INFO: db;3306;root;mangos;realmd

  server:
    tty: true
    stdin_open: true
    depends_on:
      - builder
      - db
      - realmd
    image: server
    build: ./server
    volumes:
      - maps:/etc/mangos/maps
      - vmaps:/etc/mangos/vmaps
      - mmaps:/etc/mangos/mmaps
      - dbc:/etc/mangos/dbc
    ports:
      - "8085:8085"
    restart: always
    environment:
      LOGIN_DATABASE_INFO: db;3306;root;mangos;realmd
      WORLD_DATABASE_INFO: db;3306;root;mangos;mangos3
      CHARACTER_DATABASE_INFO: db;3306;root;mangos;character3

volumes:
    db_data:
    maps:
    vmaps:
    mmaps:
    dbc: